name: Unit tests

on: 
  push: 
    branches: 
      - cicd_409455
  pull_request: 
    branches: 
      - cicd_409455

jobs: 
  tests-for-ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - name: repository copy
        uses: actions/checkout@v2
      - name: Install python for check
        uses: actions/setup-python@v3
        with: 
          python-version: "3.10"
      - name: Run tests for module
        run: |
          python -m unittest "circle_test.py"
          python -m unittest "rectangle_test.py"
          python -m unittest "square_test.py"
          python -m unittest "triangle_test.py"
  tests-for-windows:
    runs-on: windows-latest
    steps:
      - name: Clone after checkout
        uses: actions/checkout@v2
      - name: Install python for check
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run tests for module
        run: |
          python -m unittest "circle_test.py"
          python -m unittest "rectangle_test.py"
          python -m unittest "square_test.py"
          python -m unittest "triangle_test.py"  